---
- name: Add users on dev server
  hosts: dev
  vars_files:
    - user_list.yml 
    - vault/locker.yml
  tasks: 
    - name: add groups
      group:
        name: developers
        state: present
    - name: Add users
      user:
        name: "{{ item.name }}"
        password: "{{ dev_password | password_hash('sha512') }}"
        group: developers
      loop: "{{ users }}"
      when: item.job == "developer"

- name: Add users on test server
  hosts: test
  vars_files:
    - user_list.yml 
    - vault/locker.yml
  tasks: 
    - name: add groups
      group:
        name: developers
        state: present
    - name: add groups
      group:
        name: managers
        state: present

    - name: Add user with role as developer
      user:
        name: "{{ item.name }}"
        password: "{{ dev_password | password_hash('sha512') }}"
        group: developers
      loop: "{{ users }}"
      when: item.job == "developer"

    - name: Add user with role as manager
      user:
        name: "{{ item.name }}"
        password: "{{ mng_password | password_hash('sha512') }}"
        group: managers
      loop: "{{ users }}"
      when: item.job == "manager"


- name: Add users on database server
  hosts: database
  vars_files:
    - user_list.yml 
    - vault/locker.yml
  tasks: 
    - name: add groups
      group:
        name: managers
        state: present
    - name: Add users
      user:
        name: "{{ item.name }}"
        password: "{{ mng_password | password_hash('sha512') }}"
        group: managers
      loop: "{{ users }}"
      when: item.job == "manager"
